<a href="https://colab.research.google.com/github/johnmasso/Python/blob/main/Laboratorio_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importar la biblioteca pandas
import pandas as pd

# Crear un DataFrame con nombres, profesiones y países de 8 personas
data = {
    "Nombre": ["Juan", "María", "Luis", "Ana", "Carlos", "Lucía", "Pedro", "Elena"],
    "Profesión": ["Ingeniero", "Médico", "Abogado", "Profesor", "Contador", "Diseñadora", "Arquitecto", "Psicóloga"],
    "País": ["Colombia", "México", "Argentina", "Chile", "Perú", "España", "Venezuela", "Ecuador"]
}

df_personas = pd.DataFrame(data)

# Imprimir el DataFrame
print("DataFrame con nombres, profesiones y países:")
print(df_personas)


DataFrame con nombres, profesiones y países:
   Nombre   Profesión       País
0    Juan   Ingeniero   Colombia
1   María      Médico     México
2    Luis     Abogado  Argentina
3     Ana    Profesor      Chile
4  Carlos    Contador       Perú
5   Lucía  Diseñadora     España
6   Pedro  Arquitecto  Venezuela
7   Elena   Psicóloga    Ecuador


In [2]:
# Cargar un archivo CSV y mostrar las primeras 5 filas
df_csv = pd.read_csv('datos_ejemplo.csv')  # Asegúrate de subir el archivo al entorno de Colab

print("Primeras 5 filas del archivo CSV:")
print(df_csv.head(5))


Primeras 5 filas del archivo CSV:
   Estacion  Producto           Tarjeta  Integracion       Fecha  Hora  \
0  7 AGOSTO  COMUN_II  19.05.00244018-5          NaN  25/03/2024     8   
1  7 AGOSTO     COMUN  19.06.03748741-1          NaN  25/03/2024    11   
2  7 AGOSTO     COMUN  19.06.03748741-1          NaN  25/03/2024    11   
3  7 AGOSTO     COMUN  19.06.03748741-1          NaN  25/03/2024    11   
4  7 AGOSTO     COMUN  19.06.03623511-6          NaN  25/03/2024    11   

  Hora Detalle  Veh Id  Cu Farevalue  
0     08:28:11    2103           2.9  
1     11:32:07    2103           2.9  
2     11:32:11    2103           2.9  
3     11:32:18    2103           2.9  
4     11:33:13    2103           2.9  


In [3]:
# Importar numpy para generar valores aleatorios
import numpy as np

# Generar un DataFrame de 100 filas y 8 columnas con valores aleatorios
np.random.seed(0)  # Fijar la semilla para obtener resultados reproducibles
df_random = pd.DataFrame(np.random.rand(100, 8), columns=[f"Columna_{i+1}" for i in range(8)])

# Mostrar el resumen estadístico del DataFrame
print("Resumen estadístico del DataFrame aleatorio:")
print(df_random.describe())


Resumen estadístico del DataFrame aleatorio:
        Columna_1   Columna_2   Columna_3   Columna_4   Columna_5   Columna_6  \
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000   
mean     0.515153    0.499425    0.516725    0.499114    0.479604    0.464825   
std      0.270167    0.298421    0.293938    0.321437    0.293449    0.276051   
min      0.020218    0.012036    0.015606    0.004695    0.002703    0.001383   
25%      0.281974    0.275348    0.272919    0.216550    0.231410    0.253753   
50%      0.527390    0.497641    0.535905    0.473685    0.423681    0.420783   
75%      0.726438    0.732680    0.739335    0.818021    0.725781    0.650677   
max      0.976761    0.968286    0.990339    0.999278    0.988374    0.998847   

        Columna_7   Columna_8  
count  100.000000  100.000000  
mean     0.484010    0.484542  
std      0.287365    0.302694  
min      0.003860    0.035362  
25%      0.253056    0.221272  
50%      0.478725    0.433088  
7

# PARTE 2

In [5]:
# Importar la biblioteca numpy
import numpy as np

# Crear un array de números del 1 al 10
array_numeros = np.arange(1, 11)

# Calcular y mostrar la suma, media y el valor máximo del array
suma = np.sum(array_numeros)
media = np.mean(array_numeros)
maximo = np.max(array_numeros)

print("Array de números del 1 al 10:", array_numeros)
print("Suma:", suma)
print("Media:", media)
print("Valor máximo:", maximo)


Array de números del 1 al 10: [ 1  2  3  4  5  6  7  8  9 10]
Suma: 55
Media: 5.5
Valor máximo: 10


In [6]:
# Crear un array de 3x4 lleno de ceros
array_3x4 = np.zeros((3, 4))

# Cambiar la forma del array a 2x6
array_2x6 = array_3x4.reshape(2, 6)

print("Array de 3x4 lleno de ceros:")
print(array_3x4)
print("\nArray de 2x6 después de cambiar su forma:")
print(array_2x6)


Array de 3x4 lleno de ceros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array de 2x6 después de cambiar su forma:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [7]:
# Generar una matriz aleatoria de 3x3
matriz_3x3 = np.random.rand(3, 3)

# Calcular la transpuesta de la matriz
matriz_transpuesta = matriz_3x3.T

print("Matriz aleatoria de 3x3:")
print(matriz_3x3)
print("\nTranspuesta de la matriz:")
print(matriz_transpuesta)


Matriz aleatoria de 3x3:
[[0.0399928  0.63970511 0.40830291]
 [0.37740657 0.80936497 0.70903546]
 [0.95433382 0.35193624 0.89754276]]

Transpuesta de la matriz:
[[0.0399928  0.37740657 0.95433382]
 [0.63970511 0.80936497 0.35193624]
 [0.40830291 0.70903546 0.89754276]]


In [8]:
# Crear dos arrays de 5 valores cada uno
array_1 = np.array([1, 2, 3, 4, 5])
array_2 = np.array([6, 7, 8, 9, 10])

# Concatenar los dos arrays
array_concatenado = np.concatenate((array_1, array_2))

print("Primer array:", array_1)
print("Segundo array:", array_2)
print("Array concatenado:")
print(array_concatenado)


Primer array: [1 2 3 4 5]
Segundo array: [ 6  7  8  9 10]
Array concatenado:
[ 1  2  3  4  5  6  7  8  9 10]
